### ISSUE TITLE
Twitch loging issue: Any solution for this problem?

### ISSUE THREAD

**Issue by Excelsus999** [wAIfu-DEV/w-AI-fu_v2#19]
Twitch: :tmi.twitch.tv NOTICE * :Login authentication failed

**Comment by Kisahime** [comment]
seems like you might be using the wrong authentication details, I would check you are using the correct username and oauth(remember not to include the 'oauth:' part of the key)

**Comment by Excelsus999** [comment]
I don't know if it's supposed to be this one, maybe I'm missing something?:
![q](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/0477c709-26ad-4811-af4c-b2846ad0908b)
