### ISSUE TITLE
Unable to connect to eventsubs

### ISSUE THREAD

**Issue by Excelsus999** [wAIfu-DEV/w-AI-fu_v2#20]
I manage to make the bot read twitch chat but still don't read subs/follows etc...

![imagen_2023-11-18_013353362](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/14f11dda-8b41-426f-85df-765b991d55c0)

**Comment by xxandeer** [comment]
```typescript
    if (
        wAIfu.state?.auth.twitch.twitchapp_clientid === "" ||
        wAIfu.state?.auth.twitch.twitchapp_secret === ""
    ) {
        IO.warn(
            "Could not connect to Twitch EventSub.\nw-AI-fu will continue without reading follows, subs and bits.\nFollow this tutorial to enable the feature: https://github.com/wAIfu-DEV/w-AI-fu/wiki/Follower,-Subscribers,-Bits-interactions"
        );
        return false;
    }
```

Do you have any values in clientid and secret?

**Comment by wAIfu-DEV** [comment]
The 2 other instances where this message appears are there but it boils down to the ClientID and/or Secret not being correct
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/132222556/74dad4cf-e216-429a-aba7-ff30bda822ae)

**Comment by Excelsus999** [comment]
Yes I have the clientid an the secret set up
}
![LOL](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/7a3e95e9-8217-49d4-b009-74e32e862c74)

**Comment by Excelsus999** [comment]
I Resolve it but still got the Websockets connection unused error
