### ISSUE TITLE
BUG: file does not start with RIFF id / Azure tts

### ISSUE THREAD

**Issue by isaacqc1** [wAIfu-DEV/w-AI-fu_v2#23]
petit bug avec le wav qui n'est pas reconnu ou ne veut pas s'ouvrir et qui reste dans app/audio sans se supprimer ni corrompue.

Se si arriver quand AI veut lire le texte qu'Il a écrit par contre avec la command !say et le testeur tts output fonctionne sans problème ?

![Capture](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/98782434/2b6e427f-1225-4fee-8726-454517910171)
![Capture2](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/98782434/db6b1291-4791-4729-b9ff-a1b53ed50d6f)

**Comment by wAIfu-DEV** [comment]
I encountered the same issue, seems like a problem with the format of the .wav files outputed by azure. Working on it

**Comment by isaacqc1** [comment]
oki doki thanks 👍

**Comment by wAIfu-DEV** [comment]
Issue should be fixed in latest update
