### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by elixsmax1** [wAIfu-DEV/w-AI-fu_v2#24]
when i run the "Run w-AI-fu" shortcut this happens and i cannot continue, plz help.

ModuleNotFoundError: No module named 'aiohttp'

**Comment by wAIfu-DEV** [comment]
Did you run INSTALL.bat ?

**Comment by wAIfu-DEV** [comment]
and if yes, can you post a screenshot of the console with the error message?

**Comment by elixsmax1** [comment]
> and if yes, can you post a screenshot of the console with the error message?

![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/97797877/c8742142-b1b7-4d2a-83cb-08c92dec39ce)

**Comment by elixsmax1** [comment]
> and if yes, can you post a screenshot of the console with the error message?

I ran the install.bat again, could the text in red here be part of the issue? 
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/97797877/e6f72b0f-cf50-4a84-9471-aac7a6bc0db8)

**Comment by elixsmax1** [comment]
> and if yes, can you post a screenshot of the console with the error message?

I fixed the issue by running launch.bat as admin
