### ISSUE TITLE
BUG: No luck, Still can't open the app after updating

### ISSUE THREAD

**Issue by Excelsus999** [wAIfu-DEV/w-AI-fu_v2#43]
Same bug, might have to wait

**Comment by xxandeer** [comment]
Same bug does not say that much, can you provide us with a screenshot or share the content of your terminal?

**Comment by Excelsus999** [comment]
Did a fresh install too, no luck

![asdasd](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/be35c843-4cd4-4678-849a-f2ed1ff9e63c)
![ddd](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/f07aea0d-097d-4ead-a4a4-34f4331aa25e)
![dsfsdfsdfsdfsdfsdfsdf](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/e6df3fd5-ffbe-484b-8206-6b5501438d2b)
![hhh](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/0b43f380-6267-4497-8ff3-cbc5a6e99ee3)
![avassavsavasvasv](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/3111596d-51ad-4c49-a4ad-7ff79c431c99)

**Comment by xxandeer** [comment]
What version of python are you using?

**Comment by Excelsus999** [comment]
> What version of python are you using?

![dfdfddfasfwefgrvrgvw](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/38ee490d-f0b1-4e38-8d20-93e17ceb01b4)

**Comment by xxandeer** [comment]
Im using Python 3.10.11 in it works perfect
Whats your version of pip?

**Comment by Excelsus999** [comment]
> Im using Python 3.10.11 in it works perfect Whats your version of pip?

![asfwefwefpiheqwi0fbyhuoqbwyciubyqiutvbiuwevtbi](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/fd3bbe17-fb5f-4a1c-b81b-04612e5ea5a9)

**Comment by xxandeer** [comment]
Try upgrading pip
'''
python -m pip install --upgrade pip
'''

**Comment by moo7md1** [comment]
![w1](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/26189004/8df2e3a1-060d-4a0f-929b-3afad0a23f5f)
![w2](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/26189004/2451c9ff-2d9d-41dc-b497-5ccd10f2856c)

**Comment by Excelsus999** [comment]
OK it was Python, it is recommended to use: 3.10.11 and update the pip version.
