### ISSUE TITLE
file does not start with riff id / azure tts

### ISSUE THREAD

**Issue by isaacqc1** [wAIfu-DEV/w-AI-fu_v2#46]
![re](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/98782434/20734c86-244c-41d0-ac2d-0c43c2f07ce7)

new record 4 error (x

a future update for player.py ?

the strangest thing is that .wav files are still not compromised and work one time out ten (x

**Comment by wAIfu-DEV** [comment]
with which TTS does this happen?

**Comment by isaacqc1** [comment]
> with which TTS does this happen?

tested with azure fr-CA-SylvieNeural and en-CA-ClaraNeural or en-US-AvaNeural same error
​

**Comment by isaacqc1** [comment]
ah temporary fix a little delay in the voice but it works xD tabarnak 

![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/98782434/b5e32faf-65e5-4dbc-8353-c79089173830)

**Comment by isaacqc1** [comment]
yup just converting the wav to wav might be a better idea (x
