### ISSUE TITLE
BUG: W-AI-fu won’t open

### ISSUE THREAD

**Issue by gg5150** [wAIfu-DEV/w-AI-fu_v2#52]
**Describe the bug**
It refuses to load when I go to ‘launch w-AI-fu’ and it says ModuleNotFound error: No module named ‘vectordb’

**To Reproduce**
1. Go to W-AI-fu
2. Click on launch w-AI-fu shortcut
3. Wait for it to attempt to load

**Expected behavior**
I expected the GUI to open.

**Screenshots**
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/77413976/29ff563f-c8b1-4649-bdd7-04635b6b82c2)

I already updated pip and I don’t know what else to do to make it work… I’ve never coded before, and I’m having a lot of trouble. Can someone please help?

**Comment by wAIfu-DEV** [comment]
Can you try to remove the folder `source/app/vectordb/venv` and launch w-AI-fu again? This bug happens on certain machines and not on others so it's pretty confusing even for me

**Comment by gg5150** [comment]
> Can you try to remove the folder `source/app/vectordb/venv` and launch w-AI-fu again? This bug happens on certain machines and not on others so it's pretty confusing even for me

That didn’t work for me.

**Comment by gg5150** [comment]
I’m having a different problem now. It says that the model Kayra has an AttributeError?

![IMG_7665](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/77413976/12fac975-8f1f-4de7-848c-f373314d6354)
