### ISSUE TITLE
BUG: TypeError: Cannot read properties of undefined (reading 'autoPong')

### ISSUE THREAD

**Issue by Excelsus999** [wAIfu-DEV/w-AI-fu_v2#57]
Installed the new version, got this error
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/79250daf-9c75-426c-85b4-dd59621db2ba)

**Comment by Kisahime** [comment]
![Screenshot 2024-02-04 222056](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/120521433/02bfb4e0-c66b-4a15-89d8-9ab09e425533)

Getting the same error with the new version

**Comment by Excelsus999** [comment]
Nope same error

**Comment by wAIfu-DEV** [comment]
Found the issue, npm is intalling a newer (broken) version of the `ws` package.
Gotta go in the `package.json` file, and change the `"ws": "^8.14.2"` to `"ws: "8.14.2""`
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/132222556/f49d23fb-5c0f-4f9f-a128-cbf866003491)

After having done that, delete the node_modules and run INSTALL.bat again to reinstall the dependencies

**Comment by Excelsus999** [comment]
uuh IDK got this error 
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/b5422af1-ccfa-41bd-b12f-8ff72049670c)

**Comment by Excelsus999** [comment]
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/ac822220-f2a1-463c-8ea8-9cbec45d7ee0)

**Comment by Kisahime** [comment]
> Found the issue, npm is intalling a newer (broken) version of the `ws` package. Gotta go in the `package.json` file, and change the `"ws": "^8.14.2"` to `"ws: "8.14.2""` ![image](https://private-user-images.githubusercontent.com/132222556/302436805-f49d23fb-5c0f-4f9f-a128-cbf866003491.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzM5NzAsIm5iZiI6MTcwNzE3MzY3MCwicGF0aCI6Ii8xMzIyMjI1NTYvMzAyNDM2ODA1LWY0OWQyM2ZiLTVjMGYtNGY5Zi1hMTI4LWNiZjg2NjAwMzQ5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQyMjU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjdhZDIxMjhmMzRiZWY2YjRkOGE1MzljMTAzNjFkZWY0YTdjZmIwYjVmYmMwZGE4ZDFmZTRjMWUwZmYzMThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sTBVcvkC9DM4C_WMbYm3ZyO1udvw5d7P-QbOdsjrtiM)
> 
> After having done that, delete the node_modules and run INSTALL.bat again to reinstall the dependencies

Worked for me thank you

**Comment by Kisahime** [comment]
> ![image](https://private-user-images.githubusercontent.com/149912072/302450279-ac822220-f2a1-463c-8ea8-9cbec45d7ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNzM5NzAsIm5iZiI6MTcwNzE3MzY3MCwicGF0aCI6Ii8xNDk5MTIwNzIvMzAyNDUwMjc5LWFjODIyMjIwLWYyYTEtNDYzYy04ZWE4LTljYmVjNDVkN2VlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQyMjU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTk5MGI3NmFkMWI0MGY1NjAyNjdiMTEwZDk5ZmEzM2Q1ZDc2N2NlZWQxMGJjZmJhNDkwYmQ5YzI3M2RlMTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yEsDZxEAL1t-uu_yMaYcnvdq8ajwAg4kXd5T44-MCjg)

you added extra stuff to that line, should look like this
![Screenshot 2024-02-05 225544](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/120521433/1db323a9-93d2-44a7-bb32-afbf8c531d93)

**Comment by Excelsus999** [comment]
My bad it worked, thanks a lot
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/2be3291f-8525-4858-b714-bea35c606e25)

**Comment by isaacqc1** [comment]
(:
