### ISSUE TITLE
Python dependencies, even when using VENV

### ISSUE THREAD

**Issue by Salty4Daddy** [wAIfu-DEV/w-AI-fu_v2#58]
Hi. What is the reason of using venv now for all of Hilda, when we still need only and only Py310 installed? Kinda miss the point of using it, when you can't have installed anything else. 

Also, not using mini conda. Big sadge. :(

**Comment by wAIfu-DEV** [comment]
Python requires the version to be installed before creating a venv, never have I stated that it require only 310 to be installed, but it does need to be one of the installed Python versions on your system.
If you know a better way to do it, I'd gladly recruit your help ;)
