### ISSUE TITLE
BUG: [A JavaScript error occured in the main process when I tried to run the app]

### ISSUE THREAD

**Issue by asdgggg** [wAIfu-DEV/w-AI-fu_v2#63]
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/44496097/31289f42-b778-492f-a75c-11b5e292ae0f)

Any idea what I am doing wrong?

**Comment by xxandeer** [comment]
First of all is not a bug!
Your desktop is synced with OneDrive, make a dir where its not get synced by onedrive, for example C:/waifu

Hope it works ;)

**Comment by asdgggg** [comment]
Thanks and sorry for categorizing it wrong. I am new to all of this so for me if something doesn't work, it's a bug. :D Unfortunately your fix didn't help, I am getting the same error.

**Comment by xxandeer** [comment]
Did you just move the files to C root?
Make a complete new copy of the repo and reinstall everything



tors 14 mars 2024 kl. 15:25 skrev asdgggg ***@***.***>:

**Comment by xxandeer** [comment]
No problem, have a great day :)
