### ISSUE TITLE
REQUEST: Captions

### ISSUE THREAD

**Issue by asdgggg** [wAIfu-DEV/w-AI-fu_v2#65]
Can we get subtitles of what the AI is saying? I tried using speech recognition but it's not accurate

Pretty please!

**Comment by Kisahime** [comment]
This is already a feature, just need to add it as a source in OBS

**Comment by asdgggg** [comment]
> This is already a feature, just need to add it as a source in OBS

I am sure you are right, but I can't make it work. Can you help please? Thanks

**Comment by asdgggg** [comment]
I actually made it work. Didn't notice the files in the folder. :D Thanks!
