### ISSUE TITLE
BUG:  how connect w-AI-fu voice to vtube studio

### ISSUE THREAD

**Issue by mypugisold91** [wAIfu-DEV/w-AI-fu_v2#87]
**Describe the bug**
i don't know how to connect w-AI-fu voice to vtube studio

**Comment by TheRManVT** [comment]
I heard, that the character.ai connection is currently unused because their API is not public/has no documentation on how to use it.
For the voice, I prefer [VB-Audio Cable](https://vb-audio.com/Cable/index.htm) to route the output of the voice as input to VTube Studio

**Comment by mypugisold91** [comment]
i tried useing useing vb audio cables but like there are 3 outputs and i cant get them to work with vb

**Comment by mypugisold91** [comment]
ok i figured it you download this https://vb-audio.com/Cable/ and then you sent the vb cable inputs as the outputs and set the outputs as the input in vtube studio and you select simple lipsync and your good to go
