### ISSUE TITLE
Cannot open 'run w-AI-fu' shortcut

### ISSUE THREAD

**Issue by void-sys1** [wAIfu-DEV/w-AI-fu_v2#88]
![Screenshot (9)](https://github.com/user-attachments/assets/16ed4fda-5431-47a9-9f75-456398917934)
I'm getting an error as in the screenshot above when trying to open w-Ai-fu

**Comment by TheRManVT** [comment]
Delete the "node_modules" folder, open "package.json" and change the line "ws": "^8.14.2" to "ws": "8.14.2", then run INSTALL.bat again and then it should work.

Source:  [Issue #59](https://github.com/wAIfu-DEV/w-AI-fu_v2/issues/59#issuecomment-1947417028)

**Comment by void-sys1** [comment]
That worked, Thank you!

**Comment by void-sys1** [comment]
Okay, i fixed it
